### ISSUE TITLE
Admin Tab - ADP buttons

### ISSUE THREAD

**Issue by Brianklim** [IPS-Systems/Sentry_for_Drivers#57]
I would like to add 2 buttons to the Admin Tab.  First button called "ADP Timestamp" and Second button called "ADP Login" should open Incognito Chrome browser to the below URL. 

https://tlmisi2.adp.com/adptlmqts/quickTS.aspx

https://ewallet.adp.com/arcot/enroll/adpLogin.faces?TYPE=33554433&REALMOID=06-61336bb4-b012-101f-ae21-844af8f80cb3&GUID=&SMAUTHREASON=0&METHOD=GET&SMAGENTNAME=-SM-3dtuq7XzN9CwCuSW8h0Gc0h9Wvg%2bbA7DZvuZ2oVT6WtlQBwnQY0%2bfq1meN3vvgfb&TARGET=-SM-https%3a%2f%2fworkforcenow%2eadp%2ecom%2fportal%2fadmin%2ejsp

**Comment by jubayer23** [comment]
@Brianklim what will be the design of the button?

**Comment by Brianklim** [comment]
Same style as the other Admin Tab buttons.  Please use new color for these two buttons.  These two buttons should match in color.

**Comment by jubayer23** [comment]
@Brianklim There is no such methods for open the incognito mode from android app programatically.

**Comment by SarahGarren** [comment]
@jubayer23 

APD Login button should open in Puffin browser if Puffin app is installed. If Puffin app is not installed, open in Chrome. 

ADP Timestamp is good.

**Comment by jubayer23** [comment]
ADP login : puffin browser auto open isn't possible for android. So i made a chooser to choose available browser from tablet instead of this.

**Comment by SarahGarren** [comment]
QA passed.

![image](https://cloud.githubusercontent.com/assets/25572175/26764686/4ccc9cd4-4920-11e7-8e1e-8be358ebaae5.png)
