### ISSUE TITLE
Tasks - Map Route

### ISSUE THREAD

**Issue by SarahGarren** [IPS-Systems/Sentry_for_Drivers#82]
The routes to the Pick up or Drop off locations are still not showing up well. We need them to be zoomed in as much as possible without any part of the route being hidden. If there isn't a drop off location, the users current location needs to be centered on the screen, and if they are moving while on this page, the dot that represents them needs to be following them as well while they are still centered on the screen.

1- Please zoom in as much as possible. Use the extra space.

![image](https://cloud.githubusercontent.com/assets/25572175/25558982/b5a129f6-2ce6-11e7-9cb4-6ae7c31ea46e.png)

![image](https://cloud.githubusercontent.com/assets/25572175/25558991/faa01cec-2ce6-11e7-9e9e-61a9392c63be.png)

2- The map should be centered like this every time there isn't a drop off location.
 
![image](https://cloud.githubusercontent.com/assets/25572175/25264061/1ee49620-2619-11e7-93d0-1e486ed8d1b0.png)

**Comment by jubayer23** [comment]
@SarahGarren @Brianklim  how can i test this Drop Off features? can you please tell me the flow of testing?

**Comment by SarahGarren** [comment]
@jubayer23 I created 7 test tasks so you can test this. 
1- Accept task.
2- Start task by clicking green check in lower right corner.
3- On 'Pick up' and 'Drop off' page, make sure the route on the map is centered, zoomed in but not too much. User needs to be able to see whole route without any part hidden and without it being too small. User an then zoom in and out as needed.

Can't be like this. Needs to show whole route.

![image](https://cloud.githubusercontent.com/assets/25572175/26612441/a85d9946-4569-11e7-9933-42076c08aaf1.png)

If you need more Tasks to test with, let me know and I'll make them for you. And let me know any questions you have.

**Comment by SarahGarren** [comment]
@jubayer23 

1- If there is a 'Pick up' only, the first map (Pick Up page) is not centered. But the second map (Drop Off page) is centered. 

We need them both to be centered when first opened.

![image](https://cloud.githubusercontent.com/assets/25572175/26715547/f4455fd4-472a-11e7-85f3-49958695e46e.png)

2- If both 'Pick up' and 'Drop off' are defined, then first map (Pick Up page) is centered. But the second map (Drop Off page) is not centered.

We need them both to be centered when first opened.

![image](https://cloud.githubusercontent.com/assets/25572175/26715720/98598c08-472b-11e7-9ba7-1155cb3b6109.png)

**Comment by SarahGarren** [comment]
QA passed, for now.

![image](https://cloud.githubusercontent.com/assets/25572175/26765671/9da677dc-4935-11e7-8de9-f5a7b5e79f66.png)
