### ISSUE TITLE
Tasks - programmatically turn up the volume

### ISSUE THREAD

**Issue by SarahGarren** [IPS-Systems/Sentry_for_Drivers#91]
When a new task comes in, we need to make sure the user hears it at all times. So to fix this we need to make sure that even if the volume on the table is off, the volume for tasks is at max and makes noise when the new tasks comes in.

**Comment by SarahGarren** [comment]
@jubayer23 I just tested this and when the volume is all the way off on the tablet, it needs to make a noise when a new task comes in. Please do this and set the volume to max no matter what the user sets the volume on the tablet. Let me know if you need a better explanation.

**Comment by jubayer23** [comment]
Can you please tell me how you tested this.? Because i tested it and it acted as same as your expectation.

**Comment by Brianklim** [comment]
@jubayer23 , QA tested this by turning down volume using the physical button located on the side of the tablet.  QA turned down the volume until it was "muted".  Then when the tablet receives a message or task through the app there is no sound.  We want to make sure the sounds is heard anytime a message or task is received.

**Comment by SarahGarren** [comment]
@jubayer23 

Tested this and still doesn't work. Please take a look and fix. Thank you.

**Comment by SarahGarren** [comment]
QA passed.
