### ISSUE TITLE
Tasks Page - Update

### ISSUE THREAD

**Issue by SarahGarren** [IPS-Systems/Sentry_for_Drivers#93]
On the Tasks Page, we need to change a few things. 

1- We need to add a status of where the user last left off on that task. 

2- We need to change the passenger count to a little blue bow with a white number in it, and under that it needs to say 'PAX' in blue font.

![image](https://cloud.githubusercontent.com/assets/25572175/26289304/c7975436-3e53-11e7-8709-f7363b40abaf.png)

**Comment by jubayer23** [comment]
Hello , how can i get this value "where the user last left off on that task"?

**Comment by Brianklim** [comment]
Just display the string value returned from API

**Comment by jubayer23** [comment]
@Brianklim  hi i saw the API response. But there is no Left Off/ Drop Off location . There are coordinates of Drop Off location.

**Comment by SarahGarren** [comment]
@jubayer23 

Everything looks good for this, just please move the status over a little so the whole status fits on one line.

![image](https://cloud.githubusercontent.com/assets/25572175/26616973/5b1e7cea-4587-11e7-8ce8-9f5460f770a5.png)

**Comment by SarahGarren** [comment]
QA passed.

![image](https://cloud.githubusercontent.com/assets/25572175/26715078/1714e0ae-4729-11e7-9a5b-811b0c22e43d.png)
